# https://taskfile.dev

version: "3"

## —— 🎵 🐳 The Symfony Docker Takfile 🐳 🎵 ——————————————————————————————————
# https://github.com/dunglas/symfony-docker/blob/main/docs/makefile.md

vars:
    # Executables (local)
    DOCKER_COMP: docker compose

    # Docker containers
    PHP_CONT: "{{.DOCKER_COMP}} exec php"

    # Executables
    PHP: "{{.PHP_CONT}} php"
    COMPOSER: "{{.PHP_CONT}} composer"
    SYMFONY: "{{.PHP}} bin/console"

tasks:
    default:
        - task: help

    help:
        desc: Outputs this help screen
        cmds:
            - task --list
        silent: true

    ## —— Docker 🐳 ————————————————————————————————————————————————————————————————
    build:
        desc: Builds the Docker images
        cmds:
            - "{{.DOCKER_COMP}} build --pull --no-cache"

    up:
        desc: Start the docker hub in detached mode (no logs)
        cmds:
            - "{{.DOCKER_COMP}} up --detach"

    start:
        desc: Build and start the containers
        deps: [build, up]

    down:
        desc: Stop the docker hub
        cmds:
            - "{{.DOCKER_COMP}} down --remove-orphans"

    logs:
        desc: Show live logs
        cmds:
            - "{{.DOCKER_COMP}} logs --tail=0 --follow"

    sh:
        desc: Connect to the FrankenPHP container
        cmds:
            - "{{.PHP_CONT}} sh"

    bash:
        desc: Connect to the FrankenPHP container via bash so up and down arrows go to previous commands
        cmds:
            - "{{.PHP_CONT}} bash"

    test:
        desc: "Start tests with phpunit, example: task test -- --group e2e --stop-on-failure"
        cmds:
            - "{{.DOCKER_COMP}} exec --end APP_ENV=test php bin/phpunit {{.CLI_ARGS}"

    ## —— Composer 🧙 ——————————————————————————————————————————————————————————————
    composer:
        desc: "Run composer, example: task composer -- req symfony/orm-pack"
        cmds:
            - "{{.COMPOSER}} {{.CLI_ARGS}}"

    vendor:
        desc: Install vendors according to the current composer.lock file
        cmds:
            - task composer -- install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction

    ## —— Symfony 🎵 ———————————————————————————————————————————————————————————————
    sf:
        desc: "List all Symfony commands, example: task sf -- about"
        cmds:
            - "{{.SYMFONY}} {{.CLI_ARGS}}"
    cc:
        desc: Clear the cache
        cmds:
            - task sf -- c:c
